// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MacUI() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"lake relative w-full h-[30rem] md:h-96 -translate-y-48 font-bold md:h-[32rem] flex items-center justify-center\"><div class=\"absolute w-2 md:w-3 h-3/4 bg-black left-1/2 transform -translate-x-1/2\"><div class=\"absolute -left-2 md:-left-2.5 top-0 rounded-t-lg bg-black w-6 md:w-8 h-4 md:h-6\"></div><div class=\"absolute -left-24 md:-left-24 top-8 bg-blue-400 rounded-md w-48 md:w-58 h-10 md:h-12 flex items-center justify-center pl-4 text-sm md:text-base transform -rotate-2\"><span class=\"text-3xl text-white\">Hobbies</span></div><div class=\"absolute -left-24 md:-left-24 top-24 bg-red-400 rounded-md w-48 md:w-48 h-10 md:h-12 flex items-center justify-center pl-4 text-sm md:text-base transform rotate-3\"><span>Passions</span></div><div class=\"absolute -left-24 md:-left-32 top-40 bg-green-600 rounded-md w-48 md:w-64 h-10 md:h-12 flex items-center justify-center pl-4 text-sm md:text-base transform -rotate-2\"><span>Projects</span></div><div class=\"absolute -left-24 md:-left-24 top-56 bg-purple-400 rounded-md w-48 md:w-42 h-10 md:h-12 flex items-center justify-center pl-4 text-sm md:text-base transform rotate-1\"><span>Short Stories</span></div><div class=\"absolute -left-24 md:-left-32 top-72 bg-yellow-400 rounded-md w-48 md:w-64 h-10 md:h-12 flex items-center justify-center pl-4 text-sm md:text-base transform -rotate-1\"><span>Austin Insights</span></div><div class=\"absolute bg-black rounded-full w-16 md:w-24 -left-8 md:-left-12 bottom-0 h-1 md:h-2\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
